defaults:
- _self_
- optimizer: Adam
- dataset: blood
- scheduler: reduce_lr_on_plateau 

epochs: 100
accumulate: 1

data:
  batch_size: 64                # Number of examples to process in a batch during training
  eval_batch_size: 64           # Number of examples to process in a batch during evaluation (default: batch_size)

optimizer:
  lr: 0.005
  weight_decay: 1e-5

#scheduler: null
  #_target_: null
  #factor: 0.5
  #patience: 10
  #verbose: True


earlystop:
  stop: True          
  monitor: valid.loss
  mode: min
  patience: 15
  min_delta: 0.001
  store_in_memory: True
  baseline: null # 0.70 