defaults:
- _self_
- optimizer: Adam
- dataset: camelyon17
- scheduler: reduce_lr_on_plateau 

epochs: 50
accumulate: 2

dataset:
  batch_size: 128                
  eval_batch_size: 128           
  distribution_shift: False                    

optimizer:
  lr: 0.005
  weight_decay: 1e-5

scheduler:
  factor: 0.5
  patience: 10
  verbose: True