defaults:
- _self_
- optimizer: Adam
- dataset: isic2019
- scheduler: reduce_lr_on_plateau 

epochs: 120
accumulate: 1

dataset:
  batch_size: 64                
  eval_batch_size: 64           

optimizer:
  lr: 0.005
  weight_decay: 1e-5

scheduler:
  factor: 0.5
  patience: 10
  verbose: True
