defaults:
- _self_
- optimizer: Adam
- dataset: isic2019
- scheduler: multi_step_lr 

epochs: 120
accumulate: 1

dataset:
  batch_size: 64                
  eval_batch_size: 64           

optimizer:
  lr: 0.005
  weight_decay: 1e-5

scheduler:
  milestones: [35,75,90,105]
  gamma: 0.5