defaults:
- _self_
- optimizer: Adam
- dataset: iwildcam
- scheduler: multi_step_lr 

epochs: 50
accumulate: 2

dataset:
  batch_size: 128                # Number of examples to process in a batch during training
  eval_batch_size: 128           # Number of examples to process in a batch during evaluation (default: batch_size)
  distribution_shift: True                    

optimizer:
  lr: 0.01
  weight_decay: 1e-6

scheduler:
  gamma: 0.02
  milestones: [0, 25]