# @package _global_
defaults:
  - override /training: blood-training
  - override /model: eq_nasnet
  - override /training/scheduler: multi_step_lr
  - override /model/blocks_args_dict: 4blocks
  - override /wandb: default
  - _self_

model:
  dropout_rate: 0.5
  
training:
  optimizer:
    lr: 0.005
    weight_decay: 1e-5

  scheduler:
    #_target_: null
    #_target_: torch.optim.lr_scheduler.MultiStepLR
    milestones: [5,10,15,20]
    gamma: 0.5
    #patience: 10

wandb:
  project: SL-Application
  give_name: True
  tags: []


# python training/main.py other.debug=True +exp_model_specific_overwrites=eq_nasnet_DeepDRiD --info config