# @package _global_
defaults:
  - override /training: DeepDRiD-training
  - override /model: efficientnet
  - override /wandb: default
  - _self_
  
model:
  pretrained: True

training:
  optimizer:
    lr: 0.00005
    weight_decay: 0.001

  scheduler: # not used -> implement None scheduler
    patience: 99
    factor: 0.49999999999999994

  

wandb:
  project: SL-Application
  give_name: True
  tags: []
