# @package _global_
defaults:
  - override /training: blood-training
  - override /model: efficientnet
  - override /wandb: default
  - _self_
  
model:
  pretrained: True

training:
  optimizer:
    lr: 0.00742131046509759
    weight_decay: 0.00005534613181513859

  scheduler:
    factor: 0.18941789833885067
    patience: 11
    verbose: True
  
  

wandb:
  project: SL-Application
  give_name: True
  tags: []


# python training/main.py other.debug=True +exp_model_specific_overwrites=eq_nasnet_DeepDRiD --info config