# @package _global_
defaults:
  - override /training: blood-training
  - override /model: eq_nasnet
  - override /model/blocks_args_dict: 4blocks
  - override /wandb: default
  - _self_
  


training:
  optimizer:
    lr: 0.005
    weight_decay: 1e-5

  scheduler:
    _target_: null

wandb:
  project: SL-Application
  give_name: True
  tags: []


# python training/main.py other.debug=True +exp_model_specific_overwrites=eq_nasnet_DeepDRiD --info config