_target_: training.datasets.general.get_data.get_DeepDRiD
name: DeepDRiD_patient_DR_Level
mode: patient_DR_Level            
augment: 
  all:
    short_side_center_crop: True 
  train:
    ColorJitter:
      brightness: 0.4
      contrast: 0.4
      saturation: 0.4
      hue: 0.1

    #RandomResizedCrop:
    #  size: 128
    #  scale: [0.8, 1.0]

    RandomAffine:
      degrees: 180
      translate: [0.2, 0.2]
                
    RandomGrayscale:
      p: 0.2
    
                
workers: 8                 
resolution: 128
reduction_factor: 1.0

should_normalize_weights: False
channel_wise_mean_images: [0.38250651955604553, 0.23592887818813324, 0.14257268607616425]
channel_wise_std_images: [0.324453204870224, 0.21356910467147827, 0.15683040022850037]
num_channels: 3
num_classes: 5
test_as_valid: True