# @package _global_
defaults:
  - override /training: isic2019-training
  - override /model: vit
  - override /wandb: default
  - _self_
  
model:
  pretrained: False


training:
  optimizer:
    lr: 0.00011086617191327872
    weight_decay: 0.0000105649546739937

  scheduler:
    _target_: null
    #factor: 0.03079828066268554
    #patience: 65
    #verbose: True
  
wandb:
  project: SL-Application
  give_name: True
  tags: []


# python training/main.py other.debug=True +exp_model_specific_overwrites=eq_nasnet_DeepDRiD --info config