# Model parameters          
_target_: networks.EquivariantMobileNetV2            # The name of the model to use
group: cyclic  # "dihedral" "orthogonal"
rotation: 4  # discrete number or frequency
fix_params: False
restrict: [null,null,null]  # "invariant", "reflection", "halved"
channel_layout: [32, 16, 24, 32, 64, 96, 160, 320, 1280]
kernel_size: 3
bottleneck_layout: [1, 2, 3, 4, 3, 3, 1]
padding: 1
expand_ratio: 6
depth_multiplier: 1
width_multiplier: 1