# @package _global_

# example hyperparameter optimization of some experiment with Optuna:
# python train.py -m hparams_search=mnist_optuna experiment=example

defaults:
  #- override /hydra/launcher: slurm # massively parallelize the search
  - override /hydra/sweeper: ax
  - override /train: oct
  - override /train/network: eq_nasnet_pre
  - override /logger: wandb

task_name: ${logger.wandb.project}
test_mode: test
tags: ["valid/acc_weighted"]

seed: null

logger:
  wandb:
    project: "HparamsSearch"

optimized_metric: "valid/acc_weighted"

# here we define Optuna hyperparameter search
hydra:
  mode: "MULTIRUN" 
  #launcher:
  #  timeout_min: 120 # 4 hours

  sweeper:
    _target_: hydra_plugins.hydra_ax_sweeper.ax_sweeper.AxSweeper
    max_batch_size: 10 # number of parallel jobs
    ax_config:
      max_trials: 15
      early_stop:
        minimize: false
        max_epochs_without_improvement: 10
        epsilon: 1.0e-05
      experiment:
        name: deepdrip_eq_nasnet
        objective_name: ${optimized_metric}
        minimize: false
        parameter_constraints: null
        outcome_constraints: null
        status_quo: null
      client:
        verbose_logging: false
        random_seed: null
      is_noisy: true

      # define hyperparameter search space
      params:
        train.optimizer.lr: 
          type: range
          bounds: [1e-4, 0.1]
          log_scale: true
        train.optimizer.weight_decay: 
          type: range
          bounds: [1e-6, 1e-2]
          log_scale: true

