# @package _global_
defaults:
  - default
  - override /train: camelyon17

optimized_metric: "valid/loss"

hydra:
  sweeper:
    ax_config:
      early_stop:
        minimize: true
      experiment:
        name: camelyon17_HPO
        objective_name: ${optimized_metric}
        minimize: true