# @package _global_

# example hyperparameter optimization of some experiment with Optuna:
# python train.py -m hparams_search=mnist_optuna experiment=example

defaults:
  - override /hydra/sweeper: optuna
  - override /train/network: eq_nasnet
  - override /train: deepdrip
  - override /logger: wandb

task_name: ${logger.wandb.project}
test_mode: test
tags: "[valid_loss]"

train:
  trainer:
    max_epochs: 150
    #limit_train_batches: 0.01
    val_check_interval: 1.0

  network:
    dropout_rate: 0.5
    pre_trained: logs/pretrain/2024-02-25_19-32-25/checkpoints/epoch_039.ckpt

logger:
  wandb:
    project: "HparamsSearch"

# choose metric which will be optimized by Optuna
optimized_metric: "valid/loss"

# here we define Optuna hyperparameter search
hydra:
  mode: "MULTIRUN" 

  sweeper:
    _target_: hydra_plugins.hydra_optuna_sweeper.optuna_sweeper.OptunaSweeper

    # storage URL to persist optimization results
    # for example, you can use SQLite if you set 'sqlite:///example.db'
    storage: null

    # name of the study to persist optimization results
    study_name: deepdrip_eq_nasnet_pretrained

    # number of parallel workers
    n_jobs: 1

    # 'minimize' or 'maximize' the objective
    direction: minimize

    # total number of runs that will be executed
    n_trials: 30

    # choose Optuna hyperparameter sampler
    sampler:
      _target_: optuna.samplers.TPESampler
      seed: 0
      n_startup_trials: 10 # number of random sampling runs before optimization starts

    # define hyperparameter search space
    params:
      train.optimizer.lr: 'tag(log, interval(1e-4, 0.1))'
      train.optimizer.weight_decay: 'tag(log, interval(1e-6, 1e-2))'
      #train.network.dropout_rate: 'choice(0.2, 0.3, 0.4, 0.5)'
