# @package _global_

defaults:
  - default
  - override /train: isic2019_reduce_lr_on_plateau

optimized_metric: "valid/acc_weighted"

hydra:
  sweeper:
      early_stop:
        minimize: false
      experiment:
        name: isic2019_HPO
        objective_name: ${optimized_metric}
        minimize: false

      # add reduce lr on plateau to the search space
      params:
        train.scheduler.factor: 
          type: range
          bounds: [0.1, 0.9]
        train.scheduler.patience:
          type: range
          bounds: [5, 150]


