# @package _global_
defaults:
  - default
  - override /train: oct

optimized_metric: "valid/acc_weighted"

hydra:
  sweeper:
    ax_config:
      early_stop:
        minimize: false
      experiment:
        name: oct
        objective_name: ${optimized_metric}
        minimize: false

