defaults:
- _self_
- training: debug_mnist_rot
- search_space: debug
- objective: mnist_rot

exp_name: mnist_rot_test
seed: 42

training:
  training.epochs: 1
  training.steps_per_epoch: 10

generation:
  num_total_trials: 50  # total evaluation budget
  num_sobol_trials: 3
  num_fullbayesian_trials: -1
  batch_size: 1
  progress_bar: True
  num_samples: 64
  warmup_steps: 128
  #num_botorch_trials: 15

runner:
  script_path: "experiment/main.py"
  verbose: 1

other:
  evaluate_every: 50
  save_every: 1
  restart: True
  verbose: 0

wandb:
  entity: "ga92xug"
  project: "scaling-laws-nas_high_level"
  mode: disabled
  mode_runs: disabled