defaults:
- _self_
- search_space: galaxy10-5blocks
- objective: galaxy10-5blocks


exp_name: galaxy10_5blocks_weighted_folder_2
seed: 42
evaluate_only: False

training:
  model: eq_nasnet
  model.fixed_params: False
  model.stem_channels: 16
  training: galaxy10-training
  #training.epochs: 1
  #training.steps_per_epoch: -1

generation:
  num_total_trials: 100  # total evaluation budget
  num_sobol_trials: 25 # 25
  num_fullbayesian_trials: -1
  batch_size: 1
  disable_progbar: True
  num_samples: 256 
  warmup_steps: 512
  #num_botorch_trials: 15

runner:
  script_path: "experiment/main.py"
  verbose: 2

client:
  restart: True
  warm_start: galaxy10_5blocks_weighted_folder

other:
  save_every: 1
  verbose: 1
  debug: False
  fake_duplicate_trials: False

wandb:
  entity: "ga92xug"
  project: "scaling-laws-nas_high_level"
  mode: online # online
  mode_runs: disabled