defaults:
- _self_
- training: mnist_rot
- search_space: mnist_rot
- objective: mnist_rot

exp_name: mnist_rot_2
seed: 42

generation:
  num_total_trials: 50  # total evaluation budget
  num_sobol_trials: 5
  num_fullbayesian_trials: -1
  batch_size: 1
  progress_bar: False
  num_samples: 256
  warmup_steps: 512
  #num_botorch_trials: 15

runner:
  script_path: "experiment/main.py"
  verbose: 0

other:
  evaluate_every: 1
  save_every: 1
  restart: True
  verbose: 1

wandb:
  entity: "ga92xug"
  project: "scaling-laws-nas_high_level"
  mode: online
  mode_runs: disabled