_target_: torch.optim.SGD
momentum: 0.9                 # Momentum for SGD optimizer (if used)
nesterov: True                # Use Nesterov momentum for SGD optimizer (if used)
dampening: 0                  # Dampening for momentum (if used)
lr: 0.1                       # Learning rate for SGD optimizer (if used)
weight_decay: 0.0005