# @package _global_

# specify here default configuration
# order of defaults determines the order in which configs override each other
defaults:
  - _self_
  - logger: wandb # set logger here or use command line (e.g. `python train.py logger=tensorboard`)
  - hardware: gpu
  - paths: default
  - extras: default
  - hydra: default
  - train: blood

  # experiment configs allow for version control of specific hyperparameters
  # e.g. best hyperparameters for given model and datamodule
  - experiment: null

  # config for hyperparameter optimization
  - hparams_search: null

  # optional local config for machine/user specific settings
  # it's optional since it doesn't need to exist and is excluded from version control
  - local: default

  # debugging config (enable through command line, e.g. `python train.py debug=default)
  - debug: null

train:
  compile: false
  label_smoothing: 0 #.1

  trainer:
    fast_dev_run: False
    enable_model_summary: False
    accumulate_grad_batches: 1
    min_epochs: 1 # prevents early stopping
    max_epochs: 10
    enable_progress_bar: True

    # mixed precision for extra speed-up
    # precision: 16

    # perform a validation loop every N training epochs
    check_val_every_n_epoch: 1
    # How often to check the validation set. Pass a float in the range [0.0, 1.0]
    val_check_interval: 1.0

  dataset:
    test_as_valid: False  
    reduction_factor: 1
    
    workers: 8
    pin_memory: False
    persistent_workers: True

    data_dir: ${paths.data_dir}
    data:
      data_dir: ${paths.data_dir}

# task name, determines output directory path
task_name: "train"

tags: ["dev"]

train_mode: train # Options: evaluate_only, train, train_continue, train_with_pretrain
test_mode: test

# simply provide checkpoint path to resume training
ckpt_path: null

seed: 0

adversarial_attack: False # Foolbox

NAS:
  trial_index: -1