_target_: src.data.datasets.predefined.create_datasets.create_datasets
name: cifar10

augment: False
channel_wise_mean_images: [0.49137255, 0.48235294, 0.44666667]
channel_wise_std_images: [0.24705882, 0.24352941, 0.26156863]
resolution: 32

num_channels: 3
num_classes: 10

batch_size: 128                
eval_batch_size: 128 

valid_size: 0.4

should_normalize_weights: False
