defaults:
- _self_
- experiments: null

save_folder: "plotting/figures/"
textwidth_latex: 5.78853 # in inches

fontsize: 16 #12
figsize: [10, 6]

wandb_entity: ga92xug

dataset2metric: {
    # normal
    "mnist12k": "valid.acc",
    "mnist_rot": "valid.acc",
    "cifar10": "valid.acc",
    "ciar10_rot": "valid.acc",
    "blood": "valid.acc",
    "DeepDRiD": "valid.acc",

    # weighted
    "galaxy10": "valid.acc_weighted",
    "isic2019": "valid.acc_weighted",
  } 