# Training parameters
batch_size: 64                # Number of examples to process in a batch during training
eval_batch_size: 64           # Number of examples to process in a batch during evaluation (default: batch_size)
epochs: 80                    # Number of training epochs
steps_per_epoch: -1           # Number of batches to process during each epoch (-1 for all batches)
earlystop: False               # Whether to use early stopping based on a validation set
valid_metric: accuracy        # Metric to use for early stopping
eval_test: False              # Whether to evaluate on the test set during validation
accumulate: 1                 # Number of batches to accumulate gradients over before updating model
adapt_lr: validation                # Adaptive learning rate scheduler to use (exponential, validation, or Null)
lr_decay_start: 15            # Epoch to start adaptive learning rate decay
lr_decay_factor: 0.4          # Factor to multiply learning rate by during adaptive decay
lr_decay_epoch: 1             # Period (in epochs) between adaptive learning rate decay
lr_decay_schedule: null       # List of specific epochs for adaptive learning rate decay (alternative to lr_decay_epoch)
augment_train: False          
