_target_: networks.e2_wide_resnet.e2wrn28_7R
N: 8
r: 3
F: 1.
sigma: 0.45
deltaorth: True

type: Null                    # Type of fiber for the EXP model
N: Null                       # Size of cyclic group for GCNN and maximum frequency for HNET
F: Null                       # Frequency cut-off: maximum frequency at radius "r" is "F*r"
sigma: Null                   # Width of the rings building the bases (std of the gaussian window)
J: Null                       # Number of additional frequencies in the interwiners of finite groups
restrict: -1                  # Layer where to restrict SFCNN from E(2) to SE(2)
sgsize: Null                  # Number of rotations in the subgroup to restrict to in the EXP e2sfcnn models
flip: False                   # Use also reflection equivariance in the EXP model
fixparams: False              # Keep the number of parameters of the model fixed by adjusting its topology
deltaorth: False              # Use delta orthogonal initialization in conv layers
antialias: 0                  # Std for the gaussian blur in the max-pool layer. If zero (default), standard maxpooling is performed