defaults:
- _self_
- sweep_config: cifar10

num_trials: 20

sweep_config:
  program: experiment/main.py
  method: bayes

  metric:
    goal: maximize
    # name specified in the sweep-config

  early_terminate:
    type: hyperband
    # min_iter specified in the sweep-config

  # parameters specified in the sweep-config

  # model

  # percentage
  percentage:
    values: 1, 10, 25, 50, 100

  command:
    - python
    - ${program}
    - model=eq_wrn
    # same as for sweep where we searched HP for the normal data regime
    - model.restrict=[halved,halved]
