# @package _global_

# overfits to 3 batches

defaults:
  - default

training_setup:
  trainer:
    max_epochs: 10
  
  dataset:
    reduction_factor: 25

  # model ckpt and early stopping need to be disabled during overfitting
  callbacks: null

hardware:
  accelerator: gpu