defaults:
  - blocks_args_dict: 4blocks

_target_: src.networks.eq_nasnet.eq_nasnet.EquivariantNASNet
# global args
width_coefficient: 1
depth_coefficient: 1
dropout_rate: 0.2 # 0.5
stem_channels: 16 # same as wide_resnet 
fixed_params: False
eq_expand_ratio: 6
cnn_expand_ratio: 6.0
increase_blocks: null
not_increase_1_layer: False

pre_trained: null