_target_: src.data.datasets.predefined.create_datasets.create_datasets
name: ILSVRC2012

augment: 
  interpolation: BILINEAR
  train:
    RandomResizedCrop:
      size: 176
    RandomHorizontalFlip:
      p: 0.5
    TrivialAugmentWide:
      interpolation: BILINEAR
    RandomErasing:
      p: 0.1

  eval:
    short_side_center_crop:
      resize_size: 232
      crop_size: 224

resolution: 224

channel_wise_mean_images: [0.485, 0.456, 0.406]
channel_wise_std_images: [0.229, 0.224, 0.225]

num_channels: 3
num_classes: 1000

batch_size: 128                
eval_batch_size: 128 

valid_size: 0.0
test_size: 0.0

should_normalize_weights: False