_target_: src.data._datasets.med_mnist.create_datasets.create_datasets
augment: False
data_dir: 
#reduction_factor: 1
#data:
#  # for hydra call of get_data 
#  _target_: src.data._datasets.custom.get_data.get_${train.dataset.data.name}
#  resolution: ${train.dataset.resolution}
#
resolution: 28
batch_size: 64                # Number of examples to process in a batch during training
eval_batch_size: 64           # Number of examples to process in a batch during evaluation (default: batch_size)
