defaults:
- _custom_defaults
- _self_

name: OCT

augment:
  all:
    short_side_center_crop: 
      resize_size: ${train.dataset.resolution}
      crop_size: ${train.dataset.resolution}   
    Grayscale: 
      num_output_channels: 1          
resolution: 128
channel_wise_mean_images: [0.1906830072402954]  
channel_wise_std_images: [0.21406902372837067]
    
num_channels: 1
num_classes: 4

val_size: 0.1
test_size: 0.0

should_normalize_weights: True

#_target_: training.datasets.ISIC_2019.data_loader_ISIC_2019.build_isic2019_loaders
#_target_: training.datasets.general.get_data.get_OCT
#name: oct             
#augment:
#  all:
#    short_side_center_crop: True    
#    Grayscale: 
#      num_output_channels: 1          
#resolution: 128
#channel_wise_mean_images: [0.18939857184886932]  
#channel_wise_std_images: [0.2118094265460968]
#
#num_channels: 1
#num_classes: 4
#
#val_size: 0.1
#test_size: 0.0
#
#should_normalize_weights: True