defaults:
  - _self_
  - optimizer: Adam
  - dataset: camelyon17
  - scheduler: cosine_annealing_lr
  - callbacks: default
  - network: eq_nasnet

trainer:
  max_epochs: 1
  # val_check_interval: 0.25

dataset:
  batch_size: 512                

optimizer:
  lr: 0.005
  weight_decay: 1e-5

callbacks:
  model_checkpoint:
    monitor: "valid/acc"
    mode: "max"

  early_stopping:
    monitor: "valid/acc"
    patience: 2
    mode: "max"

  # batch_size_finder:
  #   _target_: lightning.pytorch.callbacks.BatchSizeFinder
  #   batch_arg_name: batch_size_per_device

