defaults:
  - _self_
  - dataset: DeepDRiD
  - callbacks: default
  - network: eq_nasnet
  - optimizer: Adam
  - scheduler: reduce_lr_on_plateau

callbacks:
  model_checkpoint:
    monitor: "valid/acc_weighted"
    mode: "max"
    save_last: True
    auto_insert_metric_name: False

  early_stopping:
    monitor: "valid/acc_weighted"
    patience: 30
    mode: "max"

scheduler: 
  factor: 0.5
  patience: 50

optimizer:
  lr: 0.001
  weight_decay: 1e-5

trainer:
  accumulate_grad_batches: 1
  max_epochs: 150


dataset:
  batch_size: 64                

