defaults:
  - dataset: imagenette
  - callbacks: default
  - network: eq_nasnet
  - optimizer: SGD
  - scheduler: cosine_annealing_lr

train_mode: train
test_mode: test

trainer:
  min_epochs: 10
  max_epochs: 50

optimizer:
  nesterov: False
  momentum: 0.9
  lr: 0.5
  weight_decay: 1e-05

dataset:
  batch_size: 128

callbacks:
  model_checkpoint:
    monitor: "valid/acc"
    mode: "max"

  early_stopping:
    monitor: "valid/acc"
    patience: 20
    mode: "max"
