defaults:
  - dataset: imagenet
  - callbacks: default
  - network: eq_nasnet
  - optimizer: SGD
  - scheduler: cosine_annealing_lr

train_mode: train
test_mode: no_test
label_smoothing: 0.1

trainer:
  min_epochs: 10
  max_epochs: 100

optimizer:
  nesterov: False
  momentum: 0.9
  lr: 0.5
  weight_decay: 1e-05

scheduler:
  warmup_epochs: 5
  warmup_decay: 0.01

dataset:
  mixup_alpha: 0.1
  cutmix_alpha: 1.0
  # we autotune the batch size to fit into memory
  batch_size: 128 # 128 * 8

  ra_sampler: True
  ra_reps: 4

  augment:
    interpolation: BILINEAR
    train:
      RandomResizedCrop:
        size: 176
      RandomHorizontalFlip:
        p: 0.5
      TrivialAugmentWide:
        interpolation: BILINEAR
      RandomErasing:
        p: 0.1

    eval:
      short_side_center_crop:
        resize_size: 232
        crop_size: 224

callbacks:
  model_checkpoint:
    monitor: "valid/acc"
    mode: "max"

  early_stopping:
    monitor: "valid/acc"
    patience: 20
    mode: "max"




