defaults:
  #- dataset/custom@dataset: isic2019 # cifar10
  - dataset: custom/cifar10
  - callbacks: none
  - network: efficientnet

_target_: src.training_loop.lightning_module.LitModule 
#_target_: src.training_loop.mnist_module.MNISTLitModule 

optimizer:
  _target_: torch.optim.Adam
  #_partial_: true
  lr: 0.001
  weight_decay: 0.0

scheduler: null
  #_target_: torch.optim.lr_scheduler.ReduceLROnPlateau
  #_partial_: true
  #mode: min
  #factor: 0.1
  #patience: 10

#net:
#  _target_: src.networks.simple_dense_net.SimpleDenseNet
#  input_size: 3072
#  lin1_size: 64
#  lin2_size: 128
#  lin3_size: 64
#  output_size: 10

#dataset:
#  _target_: src.data.mnist_datamodule.MNISTDataModule
#  data_dir: ${paths.data_dir}
#  batch_size: 128 # Needs to be divisible by the number of devices (e.g., if in a distributed setup)
#  train_val_test_split: [55_000, 5_000, 10_000]
#  num_workers: 0
#  pin_memory: False

# compile model for faster training with pytorch 2.0
compile: false