defaults:
- _self_
- callbacks: null #default
#- dataset/custom@dataset: isic2019
- dataset/predefined@dataset: cifar10
- network: efficientnet
- optimizer: Adam
- scheduler: reduce_lr_on_plateau 

_target_: src.training_loop.lightning_module.LitModule
compile: false

optimizer:
  lr: 0.005
  weight_decay: 1e-5

callbacks:
  model_checkpoint:
    monitor: "valid/acc"
    mode: "max"
    save_last: True
    auto_insert_metric_name: False

  early_stopping:
    monitor: "valid/acc"
    patience: 100
    mode: "max"

scheduler:
  metric: valid/acc
  mode: max
  factor: 0.1
  patience: 10


