defaults:
- _self_
- callbacks: 
    - model_checkpoint
    - early_stopping
    - model_summary
    - rich_progress_bar
- data: a_example
- network: eq_nasnet
- optimizer: Adam
- scheduler: reduce_lr_on_plateau 

_target_: src.models.lightning_module.LitModule
compile: false

dataset:
  batch_size: 64                # Number of examples to process in a batch during training
  eval_batch_size: 64           # Number of examples to process in a batch during evaluation (default: batch_size)

optimizer:
  lr: 0.005
  weight_decay: 1e-5

callbacks:
  model_checkpoint:
    monitor: "valid/acc"
    mode: "max"
    save_last: True
    auto_insert_metric_name: False

  early_stopping:
    monitor: "valid/acc"
    patience: 100
    mode: "max"

scheduler:
  metric: valid/loss
  mode: min
  factor: 0.1
  patience: 10


