defaults:
  - dataset: imagenet
  - callbacks: default
  - network: efficientnet
  - optimizer: Adam
  - scheduler: none


optimizer:
  lr: 0.001
  weight_decay: 0.0

# scheduler: null
#  metric: valid/acc
#  mode: max
#  factor: 0.1
#  patience: 10

callbacks:
  model_checkpoint:
    monitor: "valid/acc"
    mode: "max"
    save_last: True
    auto_insert_metric_name: False

  early_stopping:
    monitor: "valid/acc"
    patience: 100
    mode: "max"

  model_stats:
    _target_: src._callbacks.model_stats.ModelStats
    max_gflops: -1
    nas_trial: -1




