defaults:
- _self_
- optimizer: Adam
- dataset: blood
- scheduler: reduce_lr_on_plateau 

epochs: 100
accumulate: 1


data:
  batch_size: 64                # Number of examples to process in a batch during training
  eval_batch_size: 64           # Number of examples to process in a batch during evaluation (default: batch_size)

optimizer:
  lr: 0.005
  weight_decay: 1e-5

#scheduler: null
  #_target_: null
  #factor: 0.5
  #patience: 10
  #verbose: True


earlystop:
  stop: True          
  monitor: valid.loss
  mode: min
  patience: 15
  min_delta: 0.001
  store_in_memory: True
  baseline: null # 0.70 



_target_: src.models.lightning_module.LitModule

optimizer:
  _target_: torch.optim.Adam
  #_partial_: true
  lr: 0.001
  weight_decay: 0.0

scheduler:
  _target_: torch.optim.lr_scheduler.ReduceLROnPlateau
  #_partial_: true
  metric: valid/loss
  mode: min
  factor: 0.1
  patience: 10

net:
  _target_: src.models.components.simple_dense_net.SimpleDenseNet
  input_size: 784
  lin1_size: 64
  lin2_size: 128
  lin3_size: 64
  output_size: 10

# compile model for faster training with pytorch 2.0
compile: false
