defaults:
- _self_
- optimizer: Adam
- dataset: camelyon17
- scheduler: reduce_lr_on_plateau 

epochs: 5
accumulate: 1
eval_frequency: -1

dataset:
  batch_size: 32                
  eval_batch_size: 32           
  distribution_shift: False                    

optimizer:
  lr: 0.005
  weight_decay: 1e-5

scheduler:
  factor: 0.5
  patience: 2
  verbose: True