
defaults:
- _self_
- model: eq_nasnet
- training: isic2019-training
- wandb: default

# Dataset parameters        
training:
  eval_frequency: -1           # Evaluation frequency (counts iterations if positive, epochs if negative. Use -1 to evaluate at the end of each epoch)
  compile: False
  steps_per_epoch: -1
  accumulate: 1

  earlystop:
    stop: False          
    monitor: valid.acc
    mode: max
    patience: 20
    min_delta: 0.001
    store_in_memory: True

  dataset:
    data_dir: '../../Data/frischs/datasets/'  # Path to the datasets        
    workers: 8                    # Number of jobs to load the dataset
    distribution_shift: False

# Other experiment's parameters
other:
  valid_conf_matrix_frequency: 25
  backup_model: False           # Backup the model in a file
  backup_frequency: -1          # Backup frequency (counts iterations if positive, epochs if negative. Use -1 to backup at the end of each epoch)
  plot_frequency: 100           # Plot frequency (counts iterations if positive, epochs if negative. Use -1 to plot at the end of each epoch)
  store_plot: False              # Store the plot
  show: False                   # Show the plot during training
  seed: 42                      # Seed for random number generators
  output_path: 'outputs/'  # Path to the output directory
  verbose: 2                    # Verbose Level
  time_limit: null              # Maximum time limit for training (in Minutes)
  should_test: False
  gpu_time_limit: False
  debug: False

NAS:
  trial_index: -1              # -1 for this is no NAS run
  db_path: NAS/data/trial_cache.db                # Path to the database
  max_building_time: -1
  max_gflops: -1